apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "raged.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: 8080
