{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ollama
  labels:
    {{- include "raged.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: {{ .Values.ollama.storage.size }} } }
  {{- if .Values.ollama.storage.storageClassName }}
  storageClassName: {{ .Values.ollama.storage.storageClassName }}
  {{- end }}
{{- end }}
