apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: { app: {{ .Release.Name }}-postgres }
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
