apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  selector: { app: {{ .Release.Name }}-qdrant }
  ports:
    - name: http
      port: {{ .Values.qdrant.service.port }}
      targetPort: 6333
