{{- if .Values.enrichment.enabled }}
{{- if or .Values.enrichment.worker.extractor.anthropicApiKey .Values.enrichment.worker.extractor.openaiApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-secret
  labels:
    {{- include "raged.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.enrichment.worker.extractor.anthropicApiKey }}
  ANTHROPIC_API_KEY: "{{ .Values.enrichment.worker.extractor.anthropicApiKey }}"
  {{- end }}
  {{- if .Values.enrichment.worker.extractor.openaiApiKey }}
  OPENAI_API_KEY: "{{ .Values.enrichment.worker.extractor.openaiApiKey }}"
  {{- end }}
{{- end }}
{{- end }}
